# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-schemas
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-schemas
  interval: 1h
  values:
    controllers:
      k8s-schemas-server:
        type: deployment
        replicas: 1
        containers:
          caddy:
            image:
              repository: docker.io/caddy
              tag: 2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648
            env:
              XDG_DATA_HOME: /tmp/caddy-data
              XDG_CONFIG_HOME: /tmp/caddy-config
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &port 80
                    path: /
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                cpu: 50m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true

      k8s-schemas-generator:
        type: cronjob
        cronjob:
          backoffLimit: 2
          concurrencyPolicy: Forbid
          schedule: "0 */4 * * *"
          successfulJobsHistory: 0
          failedJobsHistory: 1
          startingDeadlineSeconds: 60
        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/k8s-crd-extractor
              tag: 2026.3.11@sha256:a26844ff81905a8fac4dba61b416bed087a1944e20e38634acba5a7f65eeac93
            command:
              - /usr/bin/catatonit
              - --
              - sh
            args:
              - -c
              - /app/crd-extractor.sh && exec sh /config/map/generate-index.sh
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }

    persistence:
      schemas:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          k8s-schemas-generator:
            app:
              - path: /config/.datree/crdSchemas
                subPath: crdSchemas
          k8s-schemas-server:
            caddy:
              - path: /data
                subPath: crdSchemas
                readOnly: true

      tmpfs:
        type: emptyDir
        advancedMounts:
          k8s-schemas-generator:
            app:
              - path: /tmp
                subPath: tmp
          k8s-schemas-server:
            caddy:
              - path: /tmp
                subPath: caddy-tmp

      config:
        type: configMap
        name: k8s-schemas
        advancedMounts:
          k8s-schemas-generator:
            app:
              - path: /config/map
                readOnly: true
          k8s-schemas-server:
            caddy:
              - path: /etc/caddy
                readOnly: true

    service:
      k8s-schemas:
        controller: k8s-schemas-server
        ports:
          http:
            port: *port

    route:
      http:
        kind: HTTPRoute
        hostnames:
          - "schemas.neffi.fr"
        parentRefs:
          - name: public
            namespace: network
        rules:
          - backendRefs:
              - name: k8s-schemas
                port: *port

    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534

    rbac:
      roles:
        k8s-schemas:
          type: ClusterRole
          rules:
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
                - customresourcedefinitions/status
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - apiregistration.k8s.io
              resources:
                - apiservices
                - apiservices/status
              verbs:
                - get
                - list
                - watch
      bindings:
        k8s-schemas:
          type: ClusterRoleBinding
          roleRef:
            identifier: k8s-schemas
          subjects:
            - identifier: k8s-schemas
