---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-s3-sftp-creds
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: KOPIA_SFTP_KEY_DATA
      remoteRef:
        key: "64eb8ef1-502d-40e9-aadb-b4ba00d55f57"
    - secretKey: KOPIA_SFTP_KNOWN_HOSTS
      remoteRef:
        key: "5417a855-ef8e-4d09-8c23-b4ba00dad837"
---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-s3-creds
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: ACCESS_KEY
      remoteRef:
        key: "d8a099d5-62e9-4789-b2d2-b4ba00ea0701"
    - secretKey: SECRET_KEY
      remoteRef:
        key: "c4d9f3d7-c2bc-4ac5-bb1b-b4ba00ea40d5"
