---
# yaml-language-server: $schema=https://schemas.neffi.fr/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: dufs-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: dufs
  oidc:
    provider:
      issuer: https://auth.neffi.fr/oauth2/openid/dufs
    clientID: dufs
    clientSecret:
      name: dufs-oauth-credentials
    scopes:
      - openid
      - profile
      - email
