[tools]
"cargo:kanidm_tools" = { version = "latest", locked = true }
flux2 = "latest"
kubectl = "latest"
"npm:yaml-language-server" = "latest"
oxfmt = "latest"
terraform = "latest"
terraform-ls = "latest"

[env]
KUBE_CONFIG_PATH = "~/.kube/config"
