[tools]
flux2 = "latest"
kubectl = "latest"
"npm:yaml-language-server" = "latest"
oxfmt = "latest"
terraform = "latest"
terraform-ls = "latest"

[env]
KUBECONFIG = "$HOME/.kube/config"
KUBE_CONFIG_PATH = "$HOME/.kube/config"
