---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: internal-key
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: keyId
      remoteRef:
        key: "72ddf170-07f2-4d80-8bd8-b49800b1b220"
    - secretKey: secretKey
      remoteRef:
        key: "c4f8951b-2f4f-4731-9b21-b49800b1ccbb"
---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-webui-auth
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: webuiAuthUserPass
      remoteRef:
        key: "f3351417-97ce-422d-8c01-b4ac014e08c9"
