# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "2.12.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    tolerations:
      - key: dedicated
        operator: Equal
        value: slow-node
        effect: NoSchedule
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: [raspberrypi]
    certController:
      tolerations:
        - key: dedicated
          operator: Equal
          value: slow-node
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: [raspberrypi]
    bitwarden-sdk-server:
      enabled: true
      tolerations:
        - key: dedicated
          operator: Equal
          value: slow-node
          effect: NoSchedule
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values: [raspberrypi]
