apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ovh-credentials
    creationPolicy: Owner
  data:
    - secretKey: oauth2ClientID
      remoteRef:
        key: "7a783a20-94d5-48ed-b75f-b44a00df0b8a"
    - secretKey: oauth2ClientSecret
      remoteRef:
        key: "5f56392d-43dc-421e-9194-b44a00df251d"
