server:
  externalUrl: "https://cloud.neffi.fr"
  database: "/db/database.db"
  sources:
    - path: /files
      config:
        defaultEnabled: true

http:
  trustedHeaders:
    - X-Forwarded-For
    - X-Real-IP
  disableRateLimit: false

frontend:
  name: "My Cloud"

auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      issuerUrl: "https://auth.neffi.fr/oauth2/openid/fb_quantum"
      scopes: "openid email profile groups_name"
      userIdentifier: "email"
      createUser: true
      groupsClaim: "groups"
      adminGroup: "app_admins"
      userGroups: ["fb_quantum_users"]

userDefaults:
  account:
    permissions:
      api: true
