---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: continuwuity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: CONDUWUIT_EMERGENCY_PASSWORD
      remoteRef:
        key: "6af00eca-e28c-46c4-ad33-b4a500db7cf0"
    - secretKey: CONDUWUIT_REGISTRATION_TOKEN
      remoteRef:
        key: "2fb09673-c7b7-4ae8-91be-b4a500dbbfe9"
---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-continuwuity-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
    - secretKey: client-secret
      remoteRef:
        key: "6fdf8fc0-7667-4d8f-b430-b4a500db297a"
