---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fb-quantum-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: FILEBROWSER_OIDC_CLIENT_ID
      remoteRef:
        key: "acf4b05f-b78f-4c78-88b2-b457007364b0"
    - secretKey: FILEBROWSER_OIDC_CLIENT_SECRET
      remoteRef:
        key: "ad80d021-959f-40e9-89a4-b457007375e8"
