---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pi-hole-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: FTLCONF_webserver_api_password
      remoteRef:
        key: "3b9a3124-c1a1-4b58-8a8d-b44a017088d2"
