---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ferdium
spec:
  cluster:
    name: cnpg-cluster
  name: ferdium
  owner: ferdium
  ensure: present
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo
spec:
  cluster:
    name: cnpg-cluster
  name: forgejo
  owner: forgejo
  ensure: present
