---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: envoy-gateway
      namespace: network
  interval: 1h
  path: "./kubernetes/infrastructure/network/envoy-gateway/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
  namespace: flux-system
spec:
  dependsOn:
    - name: envoy-gateway
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: public
      namespace: network
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      name: private
      namespace: network
  interval: 1h
  path: "./kubernetes/infrastructure/network/envoy-gateway/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
