---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: fb-quantum-data
spec:
  policyRef:
    name: fb-quantum-data
  schedule:
    cron: "H 4 * * *"
    jitter: 30m
    runOnCreate: false
