---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: masterkey
      remoteRef:
        key: "8d8e6d22-18eb-4787-9dbf-b45101503ea9"
    - secretKey: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
      remoteRef:
        key: "b0ae781c-43b8-4f17-a588-b45101507a8f"
    - secretKey: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME
      remoteRef:
        key: "dc138c46-8678-48b9-bf0b-b451015095bf"
    - secretKey: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME
      remoteRef:
        key: "e7aac4e3-5264-4a1d-95c1-b4510150b0ff"
    - secretKey: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS
      remoteRef:
        key: "a03d4cd9-e4f8-40fd-af0b-b4510150cd9b"
    - secretKey: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
      remoteRef:
        key: "d5155dd8-46b0-47e3-bf7f-b4510150ffa5"
    - secretKey: ZITADEL_DATABASE_POSTGRES_DSN
      remoteRef:
        key: "c7849f46-f0b3-4e03-99b5-b4530106b723"
