---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_ENDPOINT
      remoteRef:
        key: "2988cecd-00cf-417d-9489-b44b00f4ba7a"
    - secretKey: RENOVATE_PLATFORM
      remoteRef:
        key: "3e64dfb0-0c8f-4853-bdb7-b44b00f51184"
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: "b42c7c24-f5e8-4446-ac46-b44b00f0084b"
    - secretKey: RENOVATE_REPOSITORIES
      remoteRef:
        key: "e4a10e2e-386f-4dfb-8823-b44b00f5bf96"
