# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  chartRef:
    kind: OCIRepository
    name: renovate
  interval: 1h
  values:
    controllers:
      renovate:
        type: cronjob
        cronjob:
          schedule: "@hourly"
          concurrencyPolicy: Replace
          startingDeadlineSeconds: 1800
          ttlSecondsAfterFinished: 86400
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          renovate:
            image:
              repository: renovate/renovate
              tag: 44.22
            restartPolicy: Never
            env:
              TZ: Europe/Paris
              LOG_LEVEL: debug
              RENOVATE_BASE_DIR: "/tmp/renovate/"
              RENOVATE_PR_HOURLY_LIMIT: "15"
            envFrom:
              - secretRef:
                  name: renovate-credentials
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                cpu: 1500m
                memory: 1536Mi
    persistence:
      work-volume:
        enabled: true
        type: emptyDir
        advancedMounts:
          renovate:
            renovate:
              - path: /tmp/renovate/
