---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: uuid
      remoteRef:
        key: "323576b8-de0e-4acc-b85b-b4ae00e4df2c"
    - secretKey: token
      remoteRef:
        key: "dbc84c04-11c8-43ac-b99d-b4ae00e4f167"
