---
# yaml-language-server: $schema=https://schemas.neffi.fr/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts/kopiur
  ref:
    tag: "0.10.11"
    digest: sha256:fa3ed285db6a14eb943d6303b52fbb5cb6c91093277bf5dc4e8fce7b5402614e
