---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-schemas
  namespace: flux-system
spec:
  components:
    - ../../../../components/app-template
  dependsOn:
    - name: local-path
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: k8s-schemas
      namespace: selfhosted
  interval: 1h
  path: "./apps/oliver/selfhosted/k8s-schemas/app"
  postBuild:
    substitute:
      APP: k8s-schemas
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
