---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-garage-creds
  namespace: storage
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kopiur-garage-creds
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "72ddf170-07f2-4d80-8bd8-b49800b1b220"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "c4f8951b-2f4f-4731-9b21-b49800b1ccbb"
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: "606c01eb-0316-46a4-930a-b4ac015dfd9d"
---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-hetzner-1-creds
  namespace: storage
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: kopiur-hetzner-1-creds
  data:
    - secretKey: KOPIA_SFTP_KEY_DATA
      remoteRef:
        key: "64eb8ef1-502d-40e9-aadb-b4ba00d55f57"
    - secretKey: KOPIA_SFTP_KNOWN_HOSTS
      remoteRef:
        key: "5417a855-ef8e-4d09-8c23-b4ba00dad837"
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: "3780df3c-07dc-405c-acd7-b4ba00dcad35"
