---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: "194cc28a-aebd-42cc-920a-b49200b4c9e8"
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: "928b34b7-95fe-4e89-926c-b49200b4e8c6"
