# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefox
spec:
  chartRef:
    kind: OCIRepository
    name: firefox
  interval: 1h
  values:
    controllers:
      firefox:
        type: cronjob
        cronjob:
          schedule: "0 0 1 1 *"
          suspend: true
          concurrencyPolicy: Forbid
          backoffLimit: 0
          ttlSecondsAfterFinished: 3600
          successfulJobsHistory: 3
          failedJobsHistory: 1
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/firefox
              tag: 1153.0.3
            restartPolicy: Never
            env:
              - name: TZ
                value: Europe/Paris
              - name: PGID
                value: "1000"
              - name: PUID
                value: "1000"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: &httpPort 3000
                    path: /
                  initialDelaySeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
                  periodSeconds: 10
              readiness: *probe
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      firefox:
        controller: firefox
        ports:
          http:
            port: *httpPort
            protocol: TCP
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Mi
        advancedMounts:
          firefox:
            app:
              - path: /config
                subPath: config
      dshm:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
    route:
      http:
        kind: HTTPRoute
        hostnames:
          - "firefox.neffi.fr"
        parentRefs:
          - name: private
            namespace: network
        rules:
          - backendRefs:
              - name: firefox
                port: *httpPort
