---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mautrix-whatsapp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: mautrix-whatsapp
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MAUTRIX_WHATSAPP_APPSERVICE__AS_TOKEN: "{{ .as_token }}"
        MAUTRIX_WHATSAPP_APPSERVICE__HS_TOKEN: "{{ .hs_token }}"
        MAUTRIX_WHATSAPP_ENCRYPTION__PICKLE_KEY: "{{ .pickle_key }}"
        # Double-puppet appservice (id: doublepuppet) token; the trailing __NEFFI__FR becomes the
        # "neffi.fr" map key under double_puppet.secrets.
        MAUTRIX_WHATSAPP_DOUBLE_PUPPET__SECRETS__NEFFI__FR: "as_token:{{ .doublepuppet_as_token }}"
        MAUTRIX_WHATSAPP_DATABASE__URI: "postgres://mautrix_whatsapp:{{ .db_password }}@cnpg-cluster-rw.database.svc.cluster.local:5432/mautrix_whatsapp?sslmode=require"
  data:
    - secretKey: as_token
      remoteRef:
        key: "d4a5ea46-e922-4cca-9c00-b4d700bd5e26"
    - secretKey: hs_token
      remoteRef:
        key: "67b559a4-fab7-4057-a813-b4d700bd7047"
    - secretKey: pickle_key
      remoteRef:
        key: "0bd8e73c-9657-4136-954a-b4d700bbf4c9"
    - secretKey: db_password
      remoteRef:
        key: "3169eaf8-f0e7-4129-a2f2-b4d700ba9280"
    - secretKey: doublepuppet_as_token
      remoteRef:
        key: "0a6e1dc1-2e4e-4a37-b59a-b4d7013f51e1"
