---
# yaml-language-server: $schema=https://schemas.neffi.fr/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: go2rtc-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: go2rtc
  oidc:
    provider:
      issuer: https://auth.neffi.fr/oauth2/openid/go2rtc
    clientID: go2rtc
    clientSecret:
      name: go2rtc-oauth-credentials
    scopes:
      - openid
      - profile
      - email
