apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-oliver-ssd
  resources:
    requests:
      storage: 50Gi
