---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: "00917acf-50c1-44b3-98e7-b4a201714783"
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: "e98d8354-0d09-4cfb-a741-b4a201715c46"
