---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ovh-credentials
    creationPolicy: Owner
  data:
    - secretKey: oauth2ClientID
      remoteRef:
        key: "226fb5ec-0c73-4d6e-8db0-b48801643367"
    - secretKey: oauth2ClientSecret
      remoteRef:
        key: "5c7cc06f-8ae1-4ab3-a74e-b48801644b08"
