---
# yaml-language-server: $schema=https://schemas.neffi.fr/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-db-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "app"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "16dac2b7-27a7-4078-9928-b45101281d7c"
